import { AlertTriangle } from 'lucide-react'

export function DemoBanner() {
  return (
    <div className="bg-amber-50 border border-amber-400 rounded-lg p-4 flex items-start gap-3">
      <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
      <div>
        <p className="font-semibold text-amber-800">DEMO MODE — Synthetic Data</p>
        <p className="text-sm text-amber-700 mt-1">
          These results were generated by the demo engine and are entirely fabricated for UI testing purposes.
          They do not represent real proteomics data. To obtain real results, install a supported search engine
          and re-run the analysis.
        </p>
      </div>
    </div>
  )
}
